# Generated by Django 5.2.13 on 2026-04-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mileage', '0002_mileagelog_custom_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileagelog',
            name='odometer',
            field=models.PositiveIntegerField(help_text='Jelenlegi kilométeróra állás'),
        ),
    ]
