# Generated by Django 5.2.13 on 2026-04-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_insurancepolicy_custom_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancepolicy',
            options={'ordering': ['end_date'], 'verbose_name': 'Biztosítási kötvény', 'verbose_name_plural': 'Biztosítási kötvények'},
        ),
    ]
