# Generated by Django 5.2.13 on 2026-04-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('tire_replacement', 'Tire Replacement'), ('brake_service', 'Brake Service'), ('battery', 'Battery'), ('air_filter', 'Air Filter'), ('fuel_filter', 'Fuel Filter'), ('spark_plugs', 'Spark Plugs'), ('coolant', 'Coolant Flush'), ('transmission', 'Transmission Service'), ('inspection', 'Inspection / MOT'), ('repair', 'Repair'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Odometer reading at time of service (km or miles)', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of service', max_digits=8, null=True)),
                ('workshop', models.CharField(blank=True, help_text='Garage or mechanic name', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
