# Generated by Django 5.2.13 on 2026-04-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
