# Generated by Django 5.2.13 on 2026-04-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicerecorditem_and_parent_relax_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='A szerviz teljes költsége', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Kilométeróra állás a szerviz időpontjában (km vagy mérföld)', null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='workshop',
            field=models.CharField(blank=True, help_text='Garázs vagy szerelő neve', max_length=200),
        ),
    ]
