# Generated by Django 5.2.13 on 2026-04-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_custom_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='ccm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Engine (ccm)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='doors',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Doors'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-Wheel Drive (FWD)'), ('rwd', 'Rear-Wheel Drive (RWD)'), ('4x4', '4x4'), ('awd', 'All-Wheel Drive (AWD)')], max_length=10, verbose_name='Drive Type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Engine Code'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_ac',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Air Conditioning'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='hp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Horsepower (HP)'),
        ),
    ]
