# Generated by Django 5.2.13 on 2026-04-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0003_vehicle_ccm_vehicle_doors_vehicle_drive_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='clients.client', verbose_name='Client'),
        ),
    ]
