# Generated by Django 5.2.13 on 2026-04-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
        ('vehicles', '0004_vehicle_client_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='garages.garage', verbose_name='Garage'),
        ),
    ]
