# Generated by Django 5.2.13 on 2026-04-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_company_alter_client_garage'),
        ('garages', '0002_garage_is_active'),
        ('vehicles', '0005_vehicle_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='ccm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Motor (ccm)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='clients.client', verbose_name='Ügyfél'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Ajtók'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-Wheel Drive (FWD)'), ('rwd', 'Rear-Wheel Drive (RWD)'), ('4x4', '4x4'), ('awd', 'All-Wheel Drive (AWD)')], max_length=10, verbose_name='Hajtás típusa'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Motorkód'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='garages.garage', verbose_name='Garázs'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_ac',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Klíma'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='hp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teljesítmény (LE)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='17 karakteres járműazonosító szám', max_length=17, verbose_name='VIN'),
        ),
    ]
