# Generated by Django 5.2.13 on 2026-04-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('Filters', [('oil_filter', 'Oil Filter'), ('air_filter', 'Air Filter'), ('fuel_filter', 'Fuel Filter'), ('cabin_filter', 'Cabin Air Filter')]), ('Brakes', [('brake_pads_front', 'Brake Pads (Front)'), ('brake_pads_rear', 'Brake Pads (Rear)'), ('brake_discs_front', 'Brake Discs (Front)'), ('brake_discs_rear', 'Brake Discs (Rear)')]), ('Belts & Ignition', [('timing_belt', 'Timing Belt'), ('timing_chain', 'Timing Chain'), ('serpentine_belt', 'Serpentine Belt'), ('spark_plugs', 'Spark Plugs'), ('glow_plugs', 'Glow Plugs')]), ('Tyres & Electrical', [('battery', 'Battery'), ('tyre_fl', 'Tyre (Front Left)'), ('tyre_fr', 'Tyre (Front Right)'), ('tyre_rl', 'Tyre (Rear Left)'), ('tyre_rr', 'Tyre (Rear Right)'), ('wiper_blades', 'Wiper Blades')]), ('Fluids', [('coolant', 'Coolant'), ('brake_fluid', 'Brake Fluid'), ('transmission_fluid', 'Transmission Fluid')]), ('Other', [('other', 'Other')])], default='other', max_length=30)),
                ('part_name', models.CharField(help_text='Specific part name or description', max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('mileage_at_replacement', models.PositiveIntegerField(blank=True, null=True)),
                ('next_replacement_mileage', models.PositiveIntegerField(blank=True, help_text='Odometer reading when next replacement is due', null=True)),
                ('next_replacement_date', models.DateField(blank=True, help_text='Date when next replacement is due', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('workshop', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_replacements', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
