# Generated by Django 5.2.13 on 2026-04-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_partreplacement_custom_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partreplacement',
            name='next_replacement_date',
            field=models.DateField(blank=True, help_text='A következő csere esedékességének dátuma', null=True),
        ),
        migrations.AlterField(
            model_name='partreplacement',
            name='next_replacement_mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Kilométeróra állás a következő csere esedékességekor', null=True),
        ),
        migrations.AlterField(
            model_name='partreplacement',
            name='part_name',
            field=models.CharField(help_text='Konkrét alkatrésznév vagy leírás', max_length=200),
        ),
    ]
