# Generated by Django 5.2.13 on 2026-04-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0004_servicerecorditem_and_parent_relax_fields"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("title", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("total_estimate", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "service_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oil_change", "Oil Change"),
                            ("tire_rotation", "Tire Rotation"),
                            ("tire_replacement", "Tire Replacement"),
                            ("brake_service", "Brake Service"),
                            ("battery", "Battery"),
                            ("air_filter", "Air Filter"),
                            ("fuel_filter", "Fuel Filter"),
                            ("spark_plugs", "Spark Plugs"),
                            ("coolant", "Coolant Flush"),
                            ("transmission", "Transmission Service"),
                            ("inspection", "Inspection / MOT"),
                            ("repair", "Repair"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("replacement_part", models.CharField(blank=True, max_length=200)),
                ("part_price", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("consumable", models.CharField(blank=True, max_length=50)),
                ("note", models.TextField(blank=True)),
                ("work_hours", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="quotes.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
