# Generated by Django 5.2.13 on 2026-04-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        ('services', '0004_servicerecorditem_and_parent_relax_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='converted_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotes', to='services.servicerecord'),
        ),
    ]
