# Generated by Django 5.2.13 on 2026-04-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_garage'),
        ('garages', '0002_garage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cég / szervezet'),
        ),
        migrations.AlterField(
            model_name='client',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='garages.garage', verbose_name='Garázs'),
        ),
    ]
