# Generated by Django 5.2.13 on 2026-04-27 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DropdownChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_key', models.CharField(choices=[('fuel_type', 'Fuel Type'), ('transmission', 'Transmission')], max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['list_key', 'position', 'label'],
                'unique_together': {('list_key', 'value')},
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='catalog.carmake')),
            ],
            options={
                'ordering': ['position', 'name'],
                'unique_together': {('make', 'name')},
            },
        ),
    ]
