# Generated by Django 5.2.13 on 2026-04-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_initial_data'),
        ('garages', '0002_garage_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dropdownchoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carmake',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_makes', to='garages.garage'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_models', to='garages.garage'),
        ),
        migrations.AddField(
            model_name='dropdownchoice',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_dropdown_choices', to='garages.garage'),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='carmake',
            unique_together={('garage', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('garage', 'make', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='dropdownchoice',
            unique_together={('garage', 'list_key', 'value')},
        ),
    ]
