# Generated by Django 5.2.13 on 2026-04-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
