# Generated by Django 5.2.13 on 2026-04-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltinFieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(choices=[('vehicle', 'Vehicle'), ('service', 'Service Record'), ('part', 'Part Replacement'), ('mileage', 'Mileage Log'), ('insurance', 'Insurance Policy'), ('reminder', 'Reminder')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('label_override', models.CharField(blank=True, max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['form_key', 'field_name'],
                'unique_together': {('form_key', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_key', models.CharField(choices=[('vehicle', 'Vehicle'), ('service', 'Service Record'), ('part', 'Part Replacement'), ('mileage', 'Mileage Log'), ('insurance', 'Insurance Policy'), ('reminder', 'Reminder')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('field_key', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['form_key', 'position', 'label'],
                'unique_together': {('form_key', 'field_key')},
            },
        ),
    ]
