# Generated by Django 5.2.13 on 2026-04-27 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('services', 'Service Records'), ('parts', 'Part Replacements'), ('mileage', 'Mileage Log'), ('insurance', 'Insurance Policy'), ('documents', 'Documents & Images'), ('reminders', 'Reminders')], max_length=30, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['module_key'],
            },
        ),
        migrations.CreateModel(
            name='DynamicModuleField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('field_key', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formconfig.dynamicmodule')),
            ],
            options={
                'ordering': ['position', 'label'],
                'unique_together': {('module', 'field_key')},
            },
        ),
    ]
