# Generated by Django 5.2.13 on 2026-04-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formconfig', '0002_dynamicmodule_moduleconfig_dynamicmodulefield'),
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='builtinfieldconfig',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='builtinfieldconfig',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builtin_field_configs', to='garages.garage'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='garages.garage'),
        ),
        migrations.AddField(
            model_name='dynamicmodule',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_modules', to='garages.garage'),
        ),
        migrations.AddField(
            model_name='moduleconfig',
            name='garage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_configs', to='garages.garage'),
        ),
        migrations.AlterField(
            model_name='builtinfieldconfig',
            name='form_key',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('client', 'Client'), ('service', 'Service Record'), ('part', 'Part Replacement'), ('mileage', 'Mileage Log'), ('insurance', 'Insurance Policy'), ('reminder', 'Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='form_key',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('client', 'Client'), ('service', 'Service Record'), ('part', 'Part Replacement'), ('mileage', 'Mileage Log'), ('insurance', 'Insurance Policy'), ('reminder', 'Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dynamicmodule',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moduleconfig',
            name='module_key',
            field=models.CharField(choices=[('services', 'Service Records'), ('parts', 'Part Replacements'), ('mileage', 'Mileage Log'), ('insurance', 'Insurance Policy'), ('documents', 'Documents & Images'), ('reminders', 'Reminders')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='builtinfieldconfig',
            unique_together={('garage', 'form_key', 'field_name')},
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('garage', 'form_key', 'field_key')},
        ),
        migrations.AlterUniqueTogether(
            name='dynamicmodule',
            unique_together={('garage', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleconfig',
            unique_together={('garage', 'module_key')},
        ),
    ]
