# Generated by Django 5.2.13 on 2026-04-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formconfig', '0003_alter_builtinfieldconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builtinfieldconfig',
            name='form_key',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('client', 'Client'), ('service', 'Service Record'), ('quote', 'Quote'), ('part', 'Part Replacement'), ('mileage', 'Mileage Log'), ('insurance', 'Insurance Policy'), ('reminder', 'Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='form_key',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('client', 'Client'), ('service', 'Service Record'), ('quote', 'Quote'), ('part', 'Part Replacement'), ('mileage', 'Mileage Log'), ('insurance', 'Insurance Policy'), ('reminder', 'Reminder')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moduleconfig',
            name='module_key',
            field=models.CharField(choices=[('services', 'Service Records'), ('quotes', 'Quotes'), ('parts', 'Part Replacements'), ('mileage', 'Mileage Log'), ('insurance', 'Insurance Policy'), ('documents', 'Documents & Images'), ('reminders', 'Reminders')], max_length=30),
        ),
    ]
